### ISSUE TITLE
Question : Is there a no op implementation for release build ?

### ISSUE THREAD

**Issue by sid-dob** [Polidea/Cockpit#102]
`Cockpit.showCockpit(supportFragmentManager)` requires a dependency .

**Comment by martawoldanska** [comment]
`showCockpit` method is generated only in debug `Cockpit.java`. There's no no-op version of this method.

**Comment by sid-dob** [comment]
> `Cockpit.showCockpit(supportFragmentManager)` requires a dependency .

But then should we comment this line in release builds ? Will we have to change the code before building always ?
