### ISSUE TITLE
Unable to use cockpit with legacy Android Support

### ISSUE THREAD

**Issue by uKL** [Polidea/Cockpit#107]
**Describe the bug**
The application fails to build with a message (the application uses legacy support packages, not the androidx yet)
```
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
  	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
  	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:10:5-237:19 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

```

**Library version**
Version of Cockpit the issue occurs in: `3.0.1`.

**To reproduce**
1. Create project with the legacy support library (28.0.0)
2. Try using Cockpit
3. Build the app

**Expected behavior**
I could use Cockpit in projects without the androidx

**Actual behavior**
Build failed.

**Screenshots**
n/a

**Device details**
Not a device issue.

Core dependencies:
```
'com.android.tools.build:gradle:3.2.1'
Android Support 28.0.0
```

**Comment by martawoldanska** [comment]
My recommendation is to migrate to Androidx and use Jetifier to convert the libraries that still use support packages in your project. There are no plans to switch back to Android Support in Cockpit.
