### ISSUE TITLE
Missing dependency to ColorPicker

### ISSUE THREAD

**Issue by uKL** [Polidea/Cockpit#122]
**Describe the bug**
After Gradle sync and error occur `ERROR: Failed to resolve: com.github.PolideaInternal:ColorPicker:1.0.0`. As far as I understand the ColorPicker is available in JitPack only. Either promote it to JCenter or add information to the Readme to add the JitPack repository.

**Library version**
Version of Cockpit the issue occurs in: `3.1.1`.

**To reproduce**
Configure project as readme describes

**Expected behavior**
Project compiles

**Actual behavior**
Error presented

**Screenshots**
--

**Device details**
--

**Comment by martawoldanska** [comment]
@uKL Thanks!

**Comment by martawoldanska** [comment]
Fixed in 3.1.2.
