### ISSUE TITLE
Back press not handles for sub-groups

### ISSUE THREAD

**Issue by uKL** [Polidea/Cockpit#129]
**Describe the bug**
As soon as the back key (software or hardware) is pressed the cockpit fragment is closed.

**Library version**
Version of Cockpit the issue occurs in: `3.1.2`.

**To reproduce**
1. Create a configuration with
`group: "AAA/BBB`

**Expected behavior**
Navigate back to cockpit home

**Actual behavior**
Cockpit closed

**Comment by martawoldanska** [comment]
This works as intended – this mechanism assures the user doesn't get frustrated while trying to close Cockpit, with, let's say, 10 group levels. If you want to navigate back, please use navigation bar on the top.

**Comment by uKL** [comment]
That's inconsistent with Android's back key behavior. 

In fact, up should navigate away from the cockpit and back should navigate to a previous screen.

But you're the master ;-)

**Comment by martawoldanska** [comment]
Actually, in this case UX designer was the master. ;)

**Comment by uKL** [comment]
¯\_(ツ)_/¯
